services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: activiesgo-base
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=#Devdata07
    volumes:
      - sql_data:/var/opt/mssql
    restart: unless-stopped

volumes:
  sql_data:
